apiVersion: apps/v1
kind: Deployment
metadata:
        name: nginx
        namespace: default
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: nginx
        template:
                metadata:
                        labels:
                                app: nginx
                spec:
                        containers:
                        - name: name
                          image: nginx:latest
                          imagePullPolicy: Always
                          resources:
                                 requests:
                                         cpu: 100m
                                         memory: 200Mi
                          ports:
                            - containerPort: 80
apiVersion: v1
kind: Service
metadata:
        name: frontend
        namespace: default
        labels:
                app: nginx
                tier: frontend
spec:
        ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
        selector:
                app: nginx
                tier: frontend
